### ISSUE TITLE
problem in connecting to runtastic

### ISSUE THREAD

**Issue by mindi-ef** [jonasoreland/runnerup#233]
Hi,

I fill out the form for username (mail-adress) and password but if I press connect the form is closing and nothing happens. Any hints what I do wrong?

**Comment by darander** [comment]
I've seen the same issue.

The only thing I could find out while running a logcat on the latest released build, was this line:
I/Runtastic(18459): userId: null, authToken: null

(And yes, I had filled in my correct username and password for Runtastic). I don't know of this will help...

**Comment by bagage** [comment]
I can confirm that synchronize is failing because `authenticity_token` is missing from server response when doing first request.

Just after that, we have:


```if (authToken == null)
                return Status.ERROR;
```

So we never try to connect really. 

@paradix  can you look at this?

**Comment by paradix** [comment]
I could have a look, but I actually don't have an account on runtastic.

**Comment by darander** [comment]
If no-one else has issues with this, I think this issue can be closed with the latest beta-release.

**Comment by jonasoreland** [comment]
i think
https://github.com/jonasoreland/runnerup/commit/6d02fbaf4f8317592b9e73bb622119b35b006d0b
fixed it...
didn't it ?

**Comment by darander** [comment]
Yep, as far as I know. It worked flawlessly for me on the latest beta build.

I was just asking for the issue to be closed (I always like to see as few open issues as possible ;) )

**Comment by jonasoreland** [comment]
fixed

**Comment by dracorp** [comment]
Hi there
I have 1.56 version of RunnerUp and still cannot login to Runtastic.

**Comment by Bonbadil** [comment]
Hello
I'm trying RunnerUp 1.57 and when I valid the form to connect to my Runtastic account, I get a loading icon one second and I get the form again.
The official app is working on the same phone.

If I can help...
