### ISSUE TITLE
Crash on first repetition

### ISSUE THREAD

**Issue by rstruminski** [jonasoreland/runnerup#381]
[Crash Test.json.txt](https://github.com/jonasoreland/runnerup/files/235114/Crash.Test.json.txt)

When I create a workout, for example

> _5 mins activity_
> _5 mins rest_
> _repeat 3x_

only the first activity and the first rest will work. As soon as the repetition should begin, the app crashes.
(Samsung Galaxy S5 Neo, Android 5.1.1)

**Comment by lloydakis** [comment]
Same issue here. Galaxy S5 T-mobile, Android 5.1.1

**Comment by jonasoreland** [comment]
Hi
Just tested this on an android 6.0, could not reproduce...i.e no bug occurred.
Can you share your workout and upload it to this issue ?

/Jonas

**Comment by rstruminski** [comment]
Okay, I made a sample training and attached it to the first post (just remove the .txt extension).

I forgot to mention that I have Android 5.1.1, too. The bug is 100% reproducible for me. No matter what kind of training/intervals I try, it will always crash at the first repetition.

**Comment by jonasoreland** [comment]
Hi,
I published a new beta (v1.53) that I think might solve problem.
It's available for those in Runnerup-beta-testing group at google+.

If you can test, it would be much appreciated.
/Jonas

**Comment by rstruminski** [comment]
Problem still persists. On first repetition: "Runner up stopped / halted" (or whatever it is in English).

**Comment by mzandbelt** [comment]
Just to let you know, today I tried a custom made RunnerUp interval training using my Android 5.1 MotoG and I encountered the problem mentioned in this issue: warming up, first speedinterval and first recovery interval went fine, then full crash of the app (I had several repitions planned). Using the 1.54 version.

**Comment by jonasoreland** [comment]
care to share the custom made interval ? (there is an option to share via
email)

**Comment by mzandbelt** [comment]
That's a quick reply ;-) Itt was a really basic one with 5minutes warm up, 2 minutes at speed, 1 minute recovery, repeat 6 times and finish with cooling-down untill button pressed. I can try to email (which email-adress?). (I guess it would work when you manually entered all 6 repeats, but that is not what you want and that's why you introduced the repeat feature I suppose?). Still enjoying RunnerUp a lot though! ;-)

**Comment by frapro** [comment]
[753_bad.json.txt](https://github.com/jonasoreland/runnerup/files/804440/753_bad.json.txt)
[753_good.json.txt](https://github.com/jonasoreland/runnerup/files/804441/753_good.json.txt)

I'm experiencing the same problem on RunnerUp version 1.56.
It seems that when you create an activity in a repetition inside the app it doesn't get linked to the repetition in the json file.
Compare the file above, the only difference is the missing "parentGroupId":2 in the bad one.

**Comment by jonasoreland** [comment]
hi,

we you create steps inside a repeat,
you should push the (+) button on the repeat-step

otherwise the step is put outside the repeat,
and an empty repeat is created...and this cause runnerup to crash (i just
reproduced that)

does that make sense ?
can you try if you can get it to work then ?

/Jonas

**Comment by gerhardol** [comment]
Seem to be the same as #568 
Closing the older issue
